# **Introductions**

This notebook aims at building an interpretable and layered model of evictions in different scenarios (can be adjusted and defined by any interested users with different objectivs in mind). Previously, we have had a solid understanding how geo_temporal, structural vulnerability, building conditions, and tenant complaint behavior contribute to the evictions (mainly using Random Forest Regressor and some help from Linear Regression and Decision Trees). Now, we select one model (happens to be Random Forest Regressor again) for building up a function to predict. We would be able to independently (in terms of location, feature selection, and variant selections) and interactively (in terms of flexibility of parameter choice and scenario building) to predict eviction severity. By using this model to evaluate a few neighborhoods (and particular buildings, in future), we will be able to answer "What if scenarios", "which type of buildings are most resilient towards which features", "Which factors had the largest exact effect on which location/building" etc. types of questions, and therefore provide data-based insights for policy-making.


In [ ]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib
import matplotlib.pyplot as plt
import os
import io
import geopandas as gpd
import seaborn as sns
import statsmodels.api as sm
import shap
from xgboost import XGBRegressor
from scipy import stats
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_regression
from sklearn.inspection import PartialDependenceDisplay
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor

# suppress warning
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.5f}'.format)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file_path = "/content/drive/My Drive/X999/bbl_evictions_311_svi_normal_times_analysis.csv"

In [ ]:
df_raw = pd.read_csv(file_path)

In [ ]:
df = df_raw.copy()

# **Step 1: some minor adjustment of the data**

In [ ]:
df.svi_quartile.unique()
# these are strings, and will not work with the analysis.

array(['Q3', 'Q4 (High)', 'Q2', 'Q1 (Low)'], dtype=object)

In [ ]:
df.svi_quartile = df.svi_quartile.str.extract(r'Q(\d)').astype(int)

In [ ]:
df.svi_quartile.unique(), df.svi_quartile[0].dtype

(array([3, 4, 2, 1]), dtype('int64'))

In [ ]:
# list(df.columns)

# **Step 2: Model Selection: Random forest regressors/XGBoost/MLP**

In [ ]:
# xgb_model = XGBRegressor().fit()
# xgb_results = xgb_model.predict(X_test)

In [ ]:
# from a previous notebook, all in one cell for clarity:
svi_vars = ['rpl_theme1', 'rpl_theme2', 'rpl_theme3', 'rpl_theme4', 'rpl_themes', 'ep_pov150', 'ep_unemp', 'ep_nohsdp', 'ep_uninsur',
  'ep_age65', 'ep_age17', 'ep_disabl', 'ep_limeng', 'ep_noveh', 'ep_crowd', 'ep_hburd', 'ep_afam', 'ep_hisp', 'ep_asian', 'ep_aian',
  'ep_nhpi', 'ep_twomore', 'ep_otherrace', 'ep_minrty', 'ep_white', 'svi_quartile']
building_vars = ['numfloors', 'building_category_ordinal', 'unitsres', 'bldgarea', 'building_type', 'is_condo', 'is_llc',
  'style_ordinal', 'building_age', 'floor_category', 'size_quartile', 'building_size_category', 'residential_units_category']
complaints_vars = ['air_quality', 'animal_issues', 'appliances', 'building_exterior', 'doors_windows', 'electrical_issues',
  'elevator_issues', 'floors_stairs', 'general_complaints', 'graffiti_posting', 'heat_hot_water', 'homeless_issues', 'noise_complaints',
  'other_issues', 'pest_issues', 'plumbing_issues', 'police_matters', 'public_nuisance',
  'safety_concerns', 'sanitation_issues', 'walls_ceilings','total_complaints']
df['month'] = df['month_year'].str[-2:]
# they are strings
df.month = df.month.astype(int)
borough_map = {
    'MANHATTAN': 1,
    'BRONX': 2,
    'BROOKLYN': 3,
    'QUEENS': 4,
    'STATEN ISLAND': 5
}
df['borough_int'] = df['borough'].map(borough_map)
geo_temporal_vars = ['longitude','latitude', 'borough_int', 'year', 'month']
# geometry, borough, year, month_year
all_vars = svi_vars + building_vars + complaints_vars + geo_temporal_vars
# since we are already here.
X_all = df[all_vars]
y_all = df['average_year_eviction_count']
X_train_all, X_test_all, y_train_all, y_test_all = train_test_split(X_all, y_all, test_size=0.2, random_state=42)

In [ ]:
all_vars = svi_vars + building_vars + complaints_vars + geo_temporal_vars
target = 'average_year_eviction_count'

In [ ]:
nans_total = df[all_vars + [target]].isna().sum().sum()
nans_total

np.int64(0)

In [ ]:
df_model = df[all_vars + [target]]
X = df_model[all_vars]
y = df_model[target]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
xgb_model = XGBRegressor(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [ ]:
xgb_results = xgb_model.predict(X_test)
mse = mean_squared_error(y_test, xgb_results)
r2 = r2_score(y_test, xgb_results)
print(f"xgb test mse: {mse:.4f}; r-squared: {r2:.4f}")

xgb test mse: 1.7103; r-squared: 0.6474


In [ ]:
model_rfr_all = RandomForestRegressor(n_estimators=100, random_state=42)
model_rfr_all.fit(X_train_all, y_train_all)

RandomForestRegressor(random_state=42)

In [ ]:
rfr_results = model_rfr_all.predict(X_test)
mse = mean_squared_error(y_test, rfr_results)
r2 = r2_score(y_test, rfr_results)
print(f"rfr test mse: {mse:.4f}; r-squared: {r2:.4f}")
# better than xgb

rfr test mse: 1.2131; r-squared: 0.7499


**Although XGBoost is often considered a high-performance model, in our experiments, the Random Forest Regressor consistently outperformed XGBoost in both accuracy (MSE = 1.21 vs 1.71) and explanatory power (R² = 0.75 vs 0.65). Given its superior performance and greater interpretability, we adopt Random Forest as our primary model for simulation and analysis.**

In [ ]:
from sklearn.neural_network import MLPRegressor
model = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)
model.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42)

In [ ]:
mlp_results = model.predict(X_test)
mse = mean_squared_error(y_test, mlp_results)
r2 = r2_score(y_test, mlp_results)
print(f"mlp test mse: {mse:.4f}; r-squared: {r2:.4f}")
# every time it is very different

mlp test mse: 109.9637; r-squared: -21.6703


**A simple MLP's results show they were not good at all. this is not sufficient to say nn would be bad at predicting the evictions. In fact, we had some tries with Gaussian Mixture Neural Network, or GMNN, and they were good. If we do more experiments, they might be even better, but given the scope and focus of this study (not on theories of how and why nn can be fine tuned to better solve a particular social science question), we will re-direct our focus to simulation with rfr, to compare, interpret, understand, and explain the data**

In [ ]:
X_all.dtypes[X_all.dtypes == 'object']

Series([], dtype: object)

# **Step 3: Locate the POI (point of interest) in zipcodes and buildings for simulations**

In [ ]:
top_zipcodes_df = df.groupby('zipcode').size().reset_index(name='count')
top_zipcodes_df = top_zipcodes_df.sort_values(by='count', ascending=False).head(3)
top_zipcodes_df

zipcode  count
63    10458   2221
72    10467   2192
58    10453   1994

In [ ]:
# df.nta.unique()

In [ ]:
# top_nta_df = df.groupby('nta').size().reset_index(name='count')
# bottom_nta_df = top_nta_df.sort_values(by='count', ascending=False)
# bottom_nta_df

In [ ]:
top_nta_df = df.groupby('nta').size().reset_index(name='count')
top_nta_df = top_nta_df.sort_values(by='count', ascending=False).head(3)
top_nta_df
# another two neighborhoods we are going to consider is 'SoHo-TriBeCa-Civic Center-Little Italy' and 'Upper East Side-Carnegie Hill'

nta  count
27  Central Harlem North-Polo Grounds   1632
38                Crown Heights North   1599
11         Bedford Park-Fordham North   1530

In [ ]:
# picked 3 worst neighborhoods
nta_list = [#'SoHo-TriBeCa-Civic Center-Little Italy', 'Upper East Side-Carnegie Hill',
            'Central Harlem North-Polo Grounds', 'Crown Heights North', 'Bedford Park-Fordham North']

In [ ]:
top_bbls_df = df.groupby('bin').size().reset_index(name='count')
top_bbls_df = top_bbls_df.sort_values(by='count', ascending=False).head(10)
top_bbls_df

bin  count
13603  3000000    104
5362   2000000     97
13459  2127134     74
12868  2113629     67
22092  3326600     66
12453  2093973     61
21616  3253907     49
12867  2113628     48
6219   2004223     47
0      1000000     40

In [ ]:
hotspot_bins = [3000000, 2000000, 2127134, 2113629, 3326600,2093973, 3253907, 2113628, 2004223, 1000000]

In [ ]:
# def reduce_complaints(sample_row, complaint_features):
#     modified = sample_row.copy()
#     for col in complaint_features:
#         modified[col] = 0
#     return modified

In [ ]:
hotspot_samples = df[df['bin'].isin(hotspot_bins)]
hotspot_samples.head()

Unnamed: 0       primary_key         bbl court_index_number  \
122         122   011901/18_83325  2026100012          011901/18   
158         158   018569/19_99619  2026100012          018569/19   
201         201   025401/18_84954  2026100012          025401/18   
307         307  0302551/23_10953  3033700006         0302551/23   
869         869   047846/16_66997  2026100012          047846/16   

     docket_number    eviction_address eviction_apartment_number  \
122          83325   530 EAST 169TH ST                       16A   
158          99619  540 EAST 169TH ST.                       18F   
201          84954   540 EAST 169TH ST                       15K   
307          10953   435 WILSON AVENUE                        4B   
869          66997  540 EAST 169TH ST.                        8K   

    executed_date   borough  zipcode         ejectment  \
122    2019-01-17     BRONX    10456  Not an Ejectment   
158    2019-11-26     BRONX    10456  Not an Ejectment   
201    2019-02-01     BRONX    10456  Not an Ejectment   
307    2024-03-27  BROOKLYN    11221  Not an Ejectment   
869    2017-02-15     BRONX    10456  Not an Ejectment   

    eviction/legal_possession   latitude  longitude  community_board  \
122                Possession  40.832613 -73.904676              3.0   
158                Possession  40.832517 -73.904383              3.0   
201                Possession  40.832517 -73.904383              3.0   
307                Possession  40.693907 -73.913763              4.0   
869                Possession  40.832517 -73.904383              3.0   

     council_district  census_tract      bin                 nta  year  \
122              16.0         145.0  2004223  Claremont-Bathgate  2019   
158              16.0         145.0  2004223  Claremont-Bathgate  2019   
201              16.0         145.0  2004223  Claremont-Bathgate  2019   
307              37.0         435.0  3000000      Bushwick North  2024   
869              16.0         145.0  2004223  Claremont-Bathgate  2017   

    month_year                      geometry  average_year_eviction_count  \
122    2019-01  POINT (-73.904676 40.832613)                          9.4   
158    2019-11  POINT (-73.904383 40.832517)                          9.4   
201    2019-02  POINT (-73.904383 40.832517)                          9.4   
307    2024-03  POINT (-73.913763 40.693907)                         35.6   
869    2017-02  POINT (-73.904383 40.832517)                          9.4   

     yearbuilt bldgclass  numfloors  unitsres                     ownername  \
122     1965.0        D6       17.0     321.0  FORDHAM FULTON REALTY, CORP.   
158     1965.0        D6       17.0     321.0  FORDHAM FULTON REALTY, CORP.   
201     1965.0        D6       17.0     321.0  FORDHAM FULTON REALTY, CORP.   
307     2018.0        C1        4.0       9.0         WILSON REALTY USA LLC   
869     1965.0        D6       17.0     321.0  FORDHAM FULTON REALTY, CORP.   

     bldgarea  building_type building_category  is_condo  floor_category  \
122  285056.0              1          elevator         0               3   
158  285056.0              1          elevator         0               3   
201  285056.0              1          elevator         0               3   
307    8247.0              1           walk-up         0               2   
869  285056.0              1          elevator         0               3   

                            rent_era  \
122          1947–1969, rent-control   
158          1947–1969, rent-control   
201          1947–1969, rent-control   
307  1994–Present, vacancy decontrol   
869          1947–1969, rent-control   

                                   architectural_style  \
122  1951–1980, the International Style, Alternativ...   
158  1951–1980, the International Style, Alternativ...   
201  1951–1980, the International Style, Alternativ...   
307                     2001-present, New Architecture   
869  1951–1980, the International 

In [ ]:
hotspot_samples.shape

(653, 104)

In [ ]:
hotspot_samples.average_year_eviction_count.mean()
# original

np.float64(18.28820826952527)

In [ ]:
hotspot_samples = df[df['nta'].isin(nta_list)]
hotspot_samples.head()

Unnamed: 0       primary_key         bbl court_index_number  \
5            5   000098/17_69483  2031770041          000098/17   
6            6  0002959/16_69081  2033020071         0002959/16   
13          13  0012760/18_87617  1021060003         0012760/18   
24          24   002960/16_66686  2033020071          002960/16   
35          35  0052539/19_97777  3013930066         0052539/19   

    docket_number      eviction_address eviction_apartment_number  \
5           69483      65 EAST 193RD ST                        1B   
6           69081    2847 BRIGGS AVENUE              SECOND FLOOR   
13          87617    2971 EIGHTH AVENUE                       08A   
24          66686    2847 BRIGGS AVENUE               FIRST FLOOR   
35          97777  1325 EASTERN PARKWAY                       11C   

   executed_date    borough  zipcode         ejectment  \
5     2017-05-04      BRONX    10468  Not an Ejectment   
6     2017-10-03      BRONX    10458  Not an Ejectment   
13    2018-11-01  MANHATTAN    10039  Not an Ejectment   
24    2017-10-03      BRONX    10458  Not an Ejectment   
35    2019-10-25   BROOKLYN    11233  Not an Ejectment   

   eviction/legal_possession   latitude  longitude  community_board  \
5                 Possession  40.866075 -73.896515              7.0   
6                 Possession  40.869290 -73.888761              7.0   
13                Possession  40.830297 -73.936456             10.0   
24                Possession  40.869290 -73.888761              7.0   
35                Possession  40.668448 -73.924235              8.0   

    council_district  census_tract      bin  \
5               14.0         401.0  2013945   
6               15.0       40702.0  2017108   
13               9.0       24302.0  1084520   
24              15.0       40702.0  2017108   
35              41.0         359.0  3037446   

                                  nta  year month_year  \
5          Bedford Park-Fordham North  2017    2017-05   
6          Bedford Park-Fordham North  2017    2017-10   
13  Central Harlem North-Polo Grounds  2018    2018-11   
24         Bedford Park-Fordham North  2017    2017-10   
35                Crown Heights North  2019    2019-10   

                        geometry  average_year_eviction_count  yearbuilt  \
5   POINT (-73.896515 40.866075)                          1.6     1937.0   
6    POINT (-73.888761 40.86929)                          1.0     1901.0   
13  POINT (-73.936456 40.830297)                          3.0     2004.0   
24   POINT (-73.888761 40.86929)                          1.0     1901.0   
35  POINT (-73.924235 40.668448)                          1.4     1924.0   

   bldgclass  numfloors  unitsres                  ownername   bldgarea  \
5         D1        6.0      42.0        LSB HULL ASSOCIATES    37800.0   
6         B2        2.0       2.0           MAMONAU, DZMITRY     2358.0   
13        D7       30.0    1614.0      NYC HOUSING AUTHORITY  2531670.0   
24        B2        2.0       2.0           MAMONAU, DZMITRY     2358.0   
35        C1        4.0      43.0  1325 PARKWAY ESTATES, LLC    40790.0   

    building_type building_category  is_condo  floor_category  \
5               0          elevator         0               2   
6               0        two-family         0               1   
13              1          elevator         0               3   
24              0        two-family         0               1   
35              0           walk-up         0               2   

                           rent_era              architectural_style  \
5        Pre-1947, pre-rent-control      1931–1950, Manhattan Modern   
6        Pre-1947, pre-rent-control            1900–1920, Beaux-Arts   
13  1994–Present, vacancy decontrol   2001-present, New Architecture   
24       Pre-1947, pre-rent-control            1900–1920, Beaux-Arts   
35       Pre-1947, pre-rent-control  1921–1930, Art Deco Skyscrapers   

                         economic_period  resi

In [ ]:
hotspot_samples.shape
# this is why nta running the function takes much long

(4761, 104)

In [ ]:
hotspot_samples.average_year_eviction_count.mean()
# original

np.float64(1.1972694812014282)

In [ ]:
# result_df[['bin', 'original_eviction_count', 'average_year_eviction_count_c', 'reduction_in_evictions_c', 'percent_reduction_c', 'average_year_eviction_count_s', 'reduction_in_evictions_s', 'percent_reduction_s', 'original_llc_status', 'llc_change', 'average_year_eviction_count_llc', 'reduction_in_evictions_llc', 'percent_reduction_llc']].head()

bin  original_eviction_count  average_year_eviction_count_c  \
122  2004223                      9.4                       3.954198   
158  2004223                      9.4                       2.672542   
201  2004223                      9.4                       2.672542   
307  3000000                     35.6                      32.576744   
869  2004223                      9.4                       2.672542   

     reduction_in_evictions_c  percent_reduction_c  \
122                  5.445802                57.93   
158                  6.727458                71.57   
201                  6.727458                71.57   
307                  3.023256                 8.49   
869                  6.727458                71.57   

     average_year_eviction_count_s  reduction_in_evictions_s  \
122                       1.040491                  8.359509   
158                       1.335571                  8.064429   
201                       1.335571                  8.064429   
307                       8.368412                 27.231588   
869                       1.350137                  8.049863   

     percent_reduction_s  original_llc_status llc_change  \
122                88.93                  0.0  no to yes   
158                85.79                  0.0  no to yes   
201                85.79                  0.0  no to yes   
307                76.49                  1.0  yes to no   
869                85.64                  0.0  no to yes   

     average_year_eviction_count_llc  reduction_in_evictions_llc  \
122                         9.433686                   -0.033686   
158                         9.255000                    0.145000   
201                         9.372500                    0.027500   
307                        23.721512                   11.878488   
869                         9.390586                    0.009414   

     percent_reduction_llc  
122                  -0.36  
158                   1.54  
201                   0.29  
307                  33.37  
869                   0.10

In [ ]:
hotspot_bins = [ 3000000, 2000000, 2127134, 2113629, 3326600, 2093973, 3253907, 2113628, 2004223, 1000000]

# **Step 4: Create the function that takes in as many and various geo inputs, feature selections, and degrees/directions of changes. [This is the most important part]**

In [ ]:
# the core function:
# anything with None can be replaced or interchanged by another comparable parameter
def process_hotspot_counterfactuals(df, hotspot_bins=None, zip_codes=None, neighborhoods=None, rfr_model = None, feature_cols = None, complaints_vars=None, svi_vars=None, change_llc=False,
                                   # building characteristic changes (in the form of a list, a few features that are in floats. the original ones)
                                   building_change=None, building_age_change=None,
                                   # complaint modifications (in the form of a dictionary ), can change pct
                                   targeted_complaints=None, complaint_reduction_pct=None,
                                   # SVI modifications (in the form of a dictionary ), default is 0.25
                                   svi_themes=None, svi_reduction_quantile=0.25):

    # use data based on hotspot_bins or zip_codes or nta
    if hotspot_bins is not None:
        hotspot_df = df[df['bin'].isin(hotspot_bins)].copy()
    elif zip_codes is not None:
        hotspot_df = df[df['zipcode'].isin(zip_codes)].copy()
    elif neighborhoods is not None:
        hotspot_df = df[df['nta'].isin(neighborhoods)].copy()
    else:
        # if no filtering parameter is provided, use all data
        hotspot_df = df.copy()
    hotspot_df['original_eviction_count'] = hotspot_df['average_year_eviction_count'].copy()

    # variable group 1: complaints related:
    # first: process all complaints reduction (zeroing out)
    if complaints_vars:
        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            for complaint in complaints_vars:
                modified_row[complaint] = 0
            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, 'average_year_eviction_count_c'] = new_prediction

        hotspot_df['change_in_evictions_c'] = hotspot_df['original_eviction_count'] - hotspot_df['average_year_eviction_count_c']
        hotspot_df['percent_change_c'] = (hotspot_df['change_in_evictions_c'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # second: process partial complaints reduction (by percentage). percentages can be modefied
    if complaints_vars and complaint_reduction_pct:
        reduction_factor = complaint_reduction_pct / 100
        suffix = f'_c{complaint_reduction_pct}'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            for complaint in complaints_vars:
                modified_row[complaint] = row[complaint] * (1 - reduction_factor)
            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # third: select targeted complaints for reduction
    if targeted_complaints:
        # add any features
        suffix = '_targeted'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            for complaint_type, reduction_pct in targeted_complaints.items():
                if complaint_type in feature_cols:
                    reduction_factor = reduction_pct / 100
                    modified_row[complaint_type] = row[complaint_type] * (1 - reduction_factor)

            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # variable group 2: SVI related:
    # fourth: all svi change to a specific quantile
    if svi_vars:
        suffix = '_s'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            for svi in svi_vars:
                modified_row[svi] = df[svi].quantile(svi_reduction_quantile)
            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # firth: select SVI theme groups and change to a quantile (first quantile )
    if svi_themes:
        for theme_name, theme_info in svi_themes.items():
            theme_vars = theme_info['vars']
            theme_quantile = theme_info.get('quantile', 0.25)
            suffix = f'_svi_{theme_name}'

            for idx, row in hotspot_df.iterrows():
                modified_row = row.copy()
                for svi in theme_vars:
                    modified_row[svi] = df[svi].quantile(theme_quantile)
                new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
                hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

            hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
            hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # variable group 3: llc status
    # 6th:  llc status change
    if change_llc:
        suffix = '_llc'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            hotspot_df.at[idx, 'original_llc_status'] = row['is_llc']

            # flip the LLC status
            if row['is_llc'] == True:
                modified_row['is_llc'] = False
                hotspot_df.at[idx, 'llc_change'] = 'yes to no'
            else:
                modified_row['is_llc'] = True
                hotspot_df.at[idx, 'llc_change'] = 'no to yes'

            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # variable group 4: common building features related
    # 7th: process building characteristic changes by self-defined percentage
    if building_change:
        for feature, change_pct in building_change.items():
          # each feature's change and effect will be calculated and be added back to the "change in evictions {suffix}" columns etc.
            suffix = f'_{feature}'

            if feature in feature_cols:
                for idx, row in hotspot_df.iterrows():
                    modified_row = row.copy()

                    original_value = row[feature]
                    hotspot_df.at[idx, f'original_{feature}'] = original_value

                    # calculate new value based on percentage change
                    # positive percentage increases value, negative decreases
                    modified_value = original_value * (1 + (change_pct / 100))

                    # ensure non-negative values for count or size features
                    if feature in ['numfloors', 'unitsres', 'bldgarea']:
                        modified_value = max(0, modified_value)

                    modified_row[feature] = modified_value
                    hotspot_df.at[idx, f'modified_{feature}'] = modified_value

                    new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
                    hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

                hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
                hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # variable group 5: building age change (special case since it uses years not percentage)
    # 8th: building age change
    if building_age_change is not None:
        suffix = '_age'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()
            if 'building_age' in feature_cols:
                hotspot_df.at[idx, 'original_building_age'] = row['building_age']
                # can't have negative age, so use max to ensure it's not negative
                modified_row['building_age'] = max(0, row['building_age'] - building_age_change)
                hotspot_df.at[idx, 'modified_building_age'] = modified_row['building_age']
            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    # 9th: group 6 (synthesis): for combined building feature changes: if several building features were changed all at once. We need to check if there is any "synergy" or is the all changes make sense when they are together.
    # if you specify changes for multiple building characteristics in building_change, we will get individual results for each characteristic (calculated separately)
    # if we have several ones at once, we will get the individual result, and a combined result (in the format of 'suffix _bld_all') that shows what happens when all those changes are applied simultaneously
    # if you only specify one building characteristic in building_change (such as just numfloors), you'll only get the individual result for that characteristic,
    # and the combined block won't run (since there's nothing to combine).
    if building_change and len(building_change) > 1:
        suffix = '_bld_all'

        for idx, row in hotspot_df.iterrows():
            modified_row = row.copy()

            # all building changes at once
            for feature, change_pct in building_change.items():
                if feature in feature_cols:
                    original_value = row[feature]
                    modified_value = original_value * (1 + (change_pct / 100))

                    # ensure non-negative values
                    if feature in ['numfloors', 'unitsres', 'bldgarea']:
                        modified_value = max(0, modified_value)

                    modified_row[feature] = modified_value

            # apply building age change if specified
            if building_age_change is not None:
                modified_row['building_age'] = max(0, row['building_age'] - building_age_change)

            # generate prediction for all building changes combined to create a change that is less drastic than individula ones combained, probably, but makes more sense.
            new_prediction = model_rfr_all.predict([modified_row[feature_cols]])[0]
            hotspot_df.at[idx, f'average_year_eviction_count{suffix}'] = new_prediction

        # calculate changes
        hotspot_df[f'change_in_evictions{suffix}'] = hotspot_df['original_eviction_count'] - hotspot_df[f'average_year_eviction_count{suffix}']
        hotspot_df[f'percent_change{suffix}'] = (hotspot_df[f'change_in_evictions{suffix}'] / hotspot_df['original_eviction_count'] * 100).round(2)

    return hotspot_df

# **Step 5: Run the function with Geo location at some eviction-hard-hitting buildings**

In [ ]:
# call the function with a comprehensive comparsiosn output:
result_df_bins = process_hotspot_counterfactuals(
    df=df,
    hotspot_bins=hotspot_bins,
    rfr_model= model_rfr_all,
    feature_cols=all_vars,

    # bring all complaints to zero
    complaints_vars=complaints_vars,

    # reduce all complaints by 50% (total, but can also only work on one category at a time)
    complaint_reduction_pct=50,

    # targeted specific complaints with different reduction percentages
    # reduce heat/hot water complaints by 75%, reduce pest issues by 90%. plumbing iussues by 80%, noise complaints by 60%, and sanitation issues by 85%
    targeted_complaints={'heat_hot_water': 75, 'pest_issues': 90,'plumbing_issues': 80, 'noise_complaints': 60,'sanitation_issues': 85},

    # flip LLC status
    change_llc=True,

    # building physical characteristics
    # reduce floors, residential units, building area by 50%
    building_change={'numfloors': -50,'unitsres': -50,'bldgarea': -50 },

    # reduce building age by 20 years
    building_age_change=20,

    # all SVI variables to 25th percentile
    svi_vars=svi_vars,
    svi_reduction_quantile=0.25,

    # targeted specific SVI themes with different improvement levels (can change)
    # self defined
    svi_themes={'economic': {'vars': ['ep_pov150', 'ep_unemp', 'ep_nohsdp', 'ep_uninsur'],'quantile': 0.25}, 'demographic': {'vars': ['ep_age65', 'ep_age17', 'ep_disabl', 'ep_limeng'],'quantile': 0.25},
        'household': {'vars': ['ep_noveh', 'ep_crowd', 'ep_hburd'], 'quantile': 0.25}, 'racial': {'vars': ['ep_afam', 'ep_hisp', 'ep_asian', 'ep_minrty', 'ep_white'],'quantile': 0.25}})

In [ ]:
result_df_bins.to_csv('/content/drive/My Drive/X999/bins_results_df.csv')

In [ ]:
# base
summary_columns = ['bin', 'original_eviction_count']

In [ ]:
# basic intervention results
# c50 can be changed to c25 depending on how we want to reduce it
for intervention in ['c', 'c50', 'targeted', 's', 'llc']:
    summary_columns.extend([ f'average_year_eviction_count_{intervention}', f'change_in_evictions_{intervention}', f'percent_change_{intervention}'])

In [ ]:
# SVI theme results
for theme in ['economic', 'demographic', 'household', 'racial']:
    summary_columns.extend([f'average_year_eviction_count_svi_{theme}', f'change_in_evictions_svi_{theme}', f'percent_change_svi_{theme}'])

In [ ]:
# building feature results
building_features = ['numfloors', 'unitsres', 'bldgarea', 'building_age']
for feature in building_features:
    if feature == 'building_age':
        feature_suffix = 'age'
    else:
        feature_suffix = feature
    # put the original features, changed features, predicted average eviction count, changes in eviction counts, and percenaged of change together.
    summary_columns.extend([f'original_{feature}', f'modified_{feature}' if feature != 'building_age' else 'modified_building_age', f'average_year_eviction_count_{feature_suffix}',
                            f'change_in_evictions_{feature_suffix}', f'percent_change_{feature_suffix}'])

In [ ]:
# combined building changes
summary_columns.extend([ 'average_year_eviction_count_bld_all', 'change_in_evictions_bld_all', 'percent_change_bld_all'])

In [ ]:
comprehensive_summary = result_df_bins[summary_columns]

## **Step 5.1 Get the comprehensive df**

In [ ]:
comprehensive_summary

bin  original_eviction_count  average_year_eviction_count_c  \
122    2004223                      9.4                          1.444   
158    2004223                      9.4                          3.374   
201    2004223                      9.4                          1.444   
307    3000000                     35.6                         25.814   
869    2004223                      9.4                          2.264   
1075   2004223                      9.4                          1.990   
1416   1000000                     13.8                          9.478   
1931   3253907                      9.8                          1.820   
1932   3253907                      9.8                          1.820   
2541   2000000                     27.8                          3.176   
2670   2004223                      9.4                          3.918   
2671   2004223                      9.4                          1.444   
2673   2004223                      9.4                          1.992   
2867   2127134                     14.8                          2.108   
3147   2004223                      9.4                          1.996   
3317   2004223                      9.4                          1.992   
3689   2004223                      9.4                          2.266   
3885   2113629                     13.4                          1.930   
3895   2127134                     14.8                          1.964   
3897   2127134                     14.8                          3.634   
3900   2093973                     12.2                          1.906   
4271   2127134                     14.8                          1.958   
4284   2113629                     13.4                          2.486   
4285   2113629                     13.4                          2.486   
4287   2113628                      9.6                          1.858   
4414   2000000                     27.8                         15.454   
4671   2000000                     27.8                          8.884   
4705   2000000                     27.8                          8.788   
4775   2113628                      9.6                          2.688   
4777   2113629                     13.4                          1.936   
5046   2004223                      9.4                          1.442   
5050   2004223                      9.4                          1.446   
5367   2113629                     13.4                          2.758   
5372   2113628                      9.6                          2.410   
5373   2113628                      9.6                          2.410   
5375   2113629                     13.4                          2.764   
5551   2000000                     27.8                          9.088   
5674   2004223                      9.4                          1.446   
5854   2113629                     13.4                          2.774   
5914   2093973                     12.2                          2.740   
5915   2093973                     12.2                          2.740   
5916   2093973                     12.2                          2.740   
5919   2127134                     14.8                          2.512   
6551   2127134                     14.8                          2.792   
6552   2127134                     14.8                          2.792   
6553   2127134                     14.8                          4.446   
7011   2127134                     14.8                          1.964   
7045   2093973                     12.2                          3.566   
7087   2004223                      9.4                          1.446   
7114   2004223                      9.4                          1.444   
7138   2093973                     12.2                          2.462   
7142   2127134                     14.8                          2.514   
7144   2113629                     13.4                          1.942   
7147   2113628 

## **Step 5.2 Define the directional_changes function and get the result for bin df**

In [ ]:
def directional_changes(df, feature_changes, metric_cols):
    results = {}

    for metric in metric_cols:
        intervention = metric.replace('percent_change_', '')
        # positive percent_change means evictions decreased
        decreased_evictions = df[df[metric] > 0]
        increased_evictions = df[df[metric] < 0]
        no_change = df[df[metric] == 0]

        results[intervention] = {
            'total_buildings': len(df), 'decreased_evictions': {'count': len(decreased_evictions), 'percentage': round((len(decreased_evictions) / len(df) * 100), 2),
            'avg_reduction': round(decreased_evictions[metric].mean(), 2) if len(decreased_evictions) > 0 else 0 },
            'increased_evictions': {'count': len(increased_evictions), 'percentage': round((len(increased_evictions) / len(df) * 100), 2),
            'avg_increase': round(abs(increased_evictions[metric].mean()), 2) if len(increased_evictions) > 0 else 0 },
            'no_change': { 'count': len(no_change), 'percentage': round((len(no_change) / len(df) * 100), 2)}}

    return results

In [ ]:
# a dictionary noting the direction of changes applied
feature_directions = {
    # - 50%
    'numfloors': 'decrease',
    'unitsres': 'decrease',
    'bldgarea': 'decrease',
    # -20 years
    'building_age': 'decrease',
    # -50%
    'complaints': 'decrease',
    # 100%
    'complaints_100%': 'decrease',
    # to 25th percentile
    'svi': 'improve',
    # flipping
    'llc': 'toggle'
}

In [ ]:
metric_columns = ['percent_change_numfloors','percent_change_unitsres', 'percent_change_bldgarea','percent_change_age','percent_change_bld_all','percent_change_c', 'percent_change_c50',
    'percent_change_s', 'percent_change_llc']

In [ ]:
# get the directional analysis
trend_analysis = directional_changes(result_df_bins, feature_directions, metric_columns)

In [ ]:
# df
summary_rows = []
for intervention, stats in trend_analysis.items():
    summary_rows.append({
        'intervention': intervention,
        'buildings with decreased evictions (%)': stats['decreased_evictions']['percentage'],
        'average eviction reduction (%)': stats['decreased_evictions']['avg_reduction'],
        'buildings with increased evictions (%)': stats['increased_evictions']['percentage'],
        'average eviction increase (%)': stats['increased_evictions']['avg_increase']
    })

In [ ]:
trend_summary = pd.DataFrame(summary_rows)
trend_summary = trend_summary.sort_values(by='buildings with decreased evictions (%)', ascending=False)

In [ ]:
trend_summary

intervention  buildings with decreased evictions (%)  \
7            s                                  100.00   
4      bld_all                                   98.93   
6          c50                                   98.62   
5            c                                   97.86   
0    numfloors                                   88.82   
3          age                                   86.22   
1     unitsres                                   76.26   
2     bldgarea                                   42.73   
8          llc                                   42.42   

   average eviction reduction (%)  buildings with increased evictions (%)  \
7                           47.99                                    0.00   
4                           15.64                                    1.07   
6                           64.89                                    0.46   
5                           68.93                                    1.07   
0                           10.41                                    0.46   
3                           14.22                                   10.57   
1                           11.17                                    0.46   
2                           14.19                                    0.61   
8                           14.83                                    0.77   

   average eviction increase (%)  
7                           0.00  
4                          11.15  
6                          18.15  
5                          11.01  
0                          17.16  
3                          13.30  
1                          17.10  
2                          14.76  
8                          10.10

### **Short summary: so far, two very important functions have been defined: the core algo to get all kinds of senarios and the function to get the direction chanages. Any other scenarios that make sense can be derived from the core function. Now, let's do one with neighborhoods. (though the core function is compatible with zipcodes, but we would avoid doing that, because zipcodes highly overlap with neighborhoods, geographically speaking, and neighborhoods often provide a more clear and easier visual representation for human understanding.**

# **Step 6: Get results with the eviction hard hitting neighborhoods**

In [ ]:
zip_codes = [10458, 10460, 10453]
# as selected previously

In [ ]:
nta_list

['Central Harlem North-Polo Grounds',
 'Crown Heights North',
 'Bedford Park-Fordham North']

## **Step 6.1: run the model**

In [ ]:
# this result_df get the nta
result_df_nta = process_hotspot_counterfactuals(
    df=df,
    # zip_codes = [10458, 10460, 10453],
    neighborhoods= nta_list,
    # hotspot_bins=hotspot_bins,
    rfr_model= model_rfr_all,
    feature_cols=all_vars,

    # bring all complaints to zero
    complaints_vars=complaints_vars,

    # reduce all complaints by 50% (total, but can also only work on one category at a time)
    complaint_reduction_pct=50,

    # targeted specific complaints with different reduction percentages
    # reduce heat/hot water complaints by 75%, reduce pest issues by 90%. plumbing iussues by 80%, noise complaints by 60%, and sanitation issues by 85%
    targeted_complaints={'heat_hot_water': 75, 'pest_issues': 90,'plumbing_issues': 80, 'noise_complaints': 60,'sanitation_issues': 85},

    # flip LLC status
    change_llc=True,

    # building physical characteristics
    # reduce floors, residential units, building area by 50%
    building_change={'numfloors': -50,'unitsres': -50,'bldgarea': -50 },

    # reduce building age by 20 years
    building_age_change=20,

    # all SVI variables to 25th percentile
    svi_vars=svi_vars,
    svi_reduction_quantile=0.25,

    # targeted specific SVI themes with different improvement levels (can change)
    # self defined
    svi_themes={'economic': {'vars': ['ep_pov150', 'ep_unemp', 'ep_nohsdp', 'ep_uninsur'],'quantile': 0.25}, 'demographic': {'vars': ['ep_age65', 'ep_age17', 'ep_disabl', 'ep_limeng'],'quantile': 0.25},
        'household': {'vars': ['ep_noveh', 'ep_crowd', 'ep_hburd'], 'quantile': 0.25}, 'racial': {'vars': ['ep_afam', 'ep_hisp', 'ep_asian', 'ep_minrty', 'ep_white'],'quantile': 0.25}})

In [ ]:
# base
# same procedures as the bins
summary_columns = ['nta', 'original_eviction_count']

In [ ]:
# basic intervention results
# c50 can be changed to c25 depending on how we want to reduce it
for intervention in ['c', 'c50', 'targeted', 's', 'llc']:
    summary_columns.extend([ f'average_year_eviction_count_{intervention}', f'change_in_evictions_{intervention}', f'percent_change_{intervention}'])

In [ ]:
# SVI theme results
for theme in ['economic', 'demographic', 'household', 'racial']:
    summary_columns.extend([f'average_year_eviction_count_svi_{theme}', f'change_in_evictions_svi_{theme}', f'percent_change_svi_{theme}'])

In [ ]:
# building feature results
building_features = ['numfloors', 'unitsres', 'bldgarea', 'building_age']
for feature in building_features:
    if feature == 'building_age':
        feature_suffix = 'age'
    else:
        feature_suffix = feature
    # put the original features, changed features, predicted average eviction count, changes in eviction counts, and percenaged of change together.
    summary_columns.extend([f'original_{feature}', f'modified_{feature}' if feature != 'building_age' else 'modified_building_age', f'average_year_eviction_count_{feature_suffix}',
                            f'change_in_evictions_{feature_suffix}', f'percent_change_{feature_suffix}'])

In [ ]:
# combined building changes
summary_columns.extend([ 'average_year_eviction_count_bld_all', 'change_in_evictions_bld_all', 'percent_change_bld_all'])

In [ ]:
# file_path2 = '/content/drive/My Drive/X999/nta_results_df.csv'
# # result_df_nta takes a long time to run, and therefore we have saved it previously and would avoid running again.

In [ ]:
# result_df_nta = pd.read_csv(file_path2)

In [ ]:
comprehensive_summary = result_df_nta[summary_columns]

In [ ]:
comprehensive_summary.head()

nta  original_eviction_count  \
5          Bedford Park-Fordham North                  1.60000   
6          Bedford Park-Fordham North                  1.00000   
13  Central Harlem North-Polo Grounds                  3.00000   
24         Bedford Park-Fordham North                  1.00000   
35                Crown Heights North                  1.40000   

    average_year_eviction_count_c  change_in_evictions_c  percent_change_c  \
5                         4.17800               -2.57800        -161.12000   
6                         0.33400                0.66600          66.60000   
13                        2.30000                0.70000          23.33000   
24                        0.33400                0.66600          66.60000   
35                        3.97200               -2.57200        -183.71000   

    average_year_eviction_count_c50  change_in_evictions_c50  \
5                           0.64400                  0.95600   
6                           0.41400                  0.58600   
13                          2.29800                  0.70200   
24                          0.41400                  0.58600   
35                          0.70400                  0.69600   

    percent_change_c50  average_year_eviction_count_targeted  \
5             59.75000                               0.84600   
6             58.60000                               0.60200   
13            23.40000                               2.40200   
24            58.60000                               0.60200   
35            49.71000                               0.51200   

    change_in_evictions_targeted  percent_change_targeted  \
5                        0.75400                 47.12000   
6                        0.39800                 39.80000   
13                       0.59800                 19.93000   
24                       0.39800                 39.80000   
35                       0.88800                 63.43000   

    average_year_eviction_count_s  change_in_evictions_s  percent_change_s  \
5                         1.04000                0.56000          35.00000   
6                         0.33000                0.67000          67.00000   
13                        2.28200                0.71800          23.93000   
24                        0.33000                0.67000          67.00000   
35                        0.95000                0.45000          32.14000   

    average_year_eviction_count_llc  change_in_evictions_llc  \
5                           1.59200                  0.00800   
6                           0.41000                  0.59000   
13                          2.97000                  0.03000   
24                          0.41000                  0.59000   
35                          1.39800                  0.00200   

    percent_change_llc  average_year_eviction_count_svi_economic  \
5              0.50000                                   1.52800   
6             59.00000                                   0.67800   
13             1.00000                                   2.75400   
24            59.00000                                   0.67800   
35             0.14000                                   1.34400   

    change_in_evictions_svi_economic  percent_change_svi_economic  \
5                            0.07200                      4.50000   
6                            0.32200                     32.20000   
13                           0.24600                      8.20000   
24                           0.32200                     32.20000   
35                           0.05600                      4.00000   

    average_year_eviction_count_svi_demographic  \
5                                       1.45400   
6                                       0.90600   
13                                      2.96600   
24                                      0.90600   
35                                      1.32200   

    change_in_evictions_svi_demographic  perce

In [ ]:
# result_df_nta.to_csv('/content/drive/My Drive/X999/nta_results_df.csv')

In [ ]:
neighborhood_profiles = df[df['nta'].isin(nta_list)].groupby('nta').agg({
    'average_year_eviction_count': 'sum',
    'building_age': 'mean',
    'unitsres': 'mean',
    'is_llc': 'mean',
    'total_complaints': 'mean',
    # the overall SVI score
    'rpl_themes': 'mean'
})

In [ ]:
neighborhood_profiles

average_year_eviction_count  building_age  \
nta                                                                            
Bedford Park-Fordham North                          2044.40000      92.96797   
Central Harlem North-Polo Grounds                   2300.80000      89.05882   
Crown Heights North                                 1355.00000      94.20888   

                                   unitsres  is_llc  total_complaints  \
nta                                                                     
Bedford Park-Fordham North         47.15948 0.62549         269.22876   
Central Harlem North-Polo Grounds 214.38848 0.33211         662.56985   
Crown Heights North                63.22827 0.46467         202.81926   

                                   rpl_themes  
nta                                            
Bedford Park-Fordham North            0.98879  
Central Harlem North-Polo Grounds     0.96937  
Crown Heights North                   0.92978

In [ ]:
result_df_nta.head()

Unnamed: 0       primary_key         bbl court_index_number  \
5            5   000098/17_69483  2031770041          000098/17   
6            6  0002959/16_69081  2033020071         0002959/16   
13          13  0012760/18_87617  1021060003         0012760/18   
24          24   002960/16_66686  2033020071          002960/16   
35          35  0052539/19_97777  3013930066         0052539/19   

    docket_number      eviction_address eviction_apartment_number  \
5           69483      65 EAST 193RD ST                        1B   
6           69081    2847 BRIGGS AVENUE              SECOND FLOOR   
13          87617    2971 EIGHTH AVENUE                       08A   
24          66686    2847 BRIGGS AVENUE               FIRST FLOOR   
35          97777  1325 EASTERN PARKWAY                       11C   

   executed_date    borough  zipcode         ejectment  \
5     2017-05-04      BRONX    10468  Not an Ejectment   
6     2017-10-03      BRONX    10458  Not an Ejectment   
13    2018-11-01  MANHATTAN    10039  Not an Ejectment   
24    2017-10-03      BRONX    10458  Not an Ejectment   
35    2019-10-25   BROOKLYN    11233  Not an Ejectment   

   eviction/legal_possession  latitude  longitude  community_board  \
5                 Possession  40.86608  -73.89651          7.00000   
6                 Possession  40.86929  -73.88876          7.00000   
13                Possession  40.83030  -73.93646         10.00000   
24                Possession  40.86929  -73.88876          7.00000   
35                Possession  40.66845  -73.92423          8.00000   

    council_district  census_tract      bin  \
5           14.00000     401.00000  2013945   
6           15.00000   40702.00000  2017108   
13           9.00000   24302.00000  1084520   
24          15.00000   40702.00000  2017108   
35          41.00000     359.00000  3037446   

                                  nta  year month_year  \
5          Bedford Park-Fordham North  2017    2017-05   
6          Bedford Park-Fordham North  2017    2017-10   
13  Central Harlem North-Polo Grounds  2018    2018-11   
24         Bedford Park-Fordham North  2017    2017-10   
35                Crown Heights North  2019    2019-10   

                        geometry  average_year_eviction_count  yearbuilt  \
5   POINT (-73.896515 40.866075)                      1.60000 1937.00000   
6    POINT (-73.888761 40.86929)                      1.00000 1901.00000   
13  POINT (-73.936456 40.830297)                      3.00000 2004.00000   
24   POINT (-73.888761 40.86929)                      1.00000 1901.00000   
35  POINT (-73.924235 40.668448)                      1.40000 1924.00000   

   bldgclass  numfloors   unitsres                  ownername      bldgarea  \
5         D1    6.00000   42.00000        LSB HULL ASSOCIATES   37800.00000   
6         B2    2.00000    2.00000           MAMONAU, DZMITRY    2358.00000   
13        D7   30.00000 1614.00000      NYC HOUSING AUTHORITY 2531670.00000   
24        B2    2.00000    2.00000           MAMONAU, DZMITRY    2358.00000   
35        C1    4.00000   43.00000  1325 PARKWAY ESTATES, LLC   40790.00000   

    building_type building_category  is_condo  floor_category  \
5               0          elevator         0               2   
6               0        two-family         0               1   
13              1          elevator         0               3   
24              0        two-family         0               1   
35              0           walk-up         0               2   

                           rent_era              architectural_style  \
5        Pre-1947, pre-rent-control      1931–1950, Manhattan Modern   
6        Pre-1947, pre-rent-control            1900–1920, Beaux-Arts   
13  1994–Present, vacancy decontrol   2001-present, New Architecture   
24       Pre-1947, pre-rent-control            1900–1920, Beaux-Arts   
35       Pre-1947, pre-rent-control  1921–1930, Art Deco Skyscrapers   

                         eco

## **Step 6.2: Change of Directions analysis**

In [ ]:
metric_columns

['percent_change_numfloors',
 'percent_change_unitsres',
 'percent_change_bldgarea',
 'percent_change_age',
 'percent_change_bld_all',
 'percent_change_c',
 'percent_change_c50',
 'percent_change_s',
 'percent_change_llc']

In [ ]:
metric_columns2 = ['average_year_eviction_count_c', 'change_in_evictions_c', 'percent_change_c', 'average_year_eviction_count_c50', 'change_in_evictions_c50',
 'percent_change_c50', 'average_year_eviction_count_targeted', 'change_in_evictions_targeted', 'percent_change_targeted','average_year_eviction_count_s',
 'change_in_evictions_s', 'percent_change_s', 'average_year_eviction_count_svi_economic', 'change_in_evictions_svi_economic','percent_change_svi_economic',
 'average_year_eviction_count_svi_demographic', 'change_in_evictions_svi_demographic', 'percent_change_svi_demographic', 'average_year_eviction_count_svi_household',
 'change_in_evictions_svi_household','percent_change_svi_household', 'average_year_eviction_count_svi_racial', 'change_in_evictions_svi_racial',
 'percent_change_svi_racial', 'original_llc_status', 'llc_change', 'average_year_eviction_count_llc', 'change_in_evictions_llc','percent_change_llc',
'original_numfloors', 'modified_numfloors','average_year_eviction_count_numfloors']

In [ ]:
missing_cols = [col for col in metric_columns2 if col not in result_df_nta.columns]
missing_cols
# good

[]

In [ ]:
# list(result_df_nta.columns)[:-20]

In [ ]:
trend_analysis_nta = directional_changes(result_df_nta, feature_directions, metric_columns2)

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
result_df_nta[metric_columns2].dtypes

average_year_eviction_count_c                  float64
change_in_evictions_c                          float64
percent_change_c                               float64
average_year_eviction_count_c50                float64
change_in_evictions_c50                        float64
percent_change_c50                             float64
average_year_eviction_count_targeted           float64
change_in_evictions_targeted                   float64
percent_change_targeted                        float64
average_year_eviction_count_s                  float64
change_in_evictions_s                          float64
percent_change_s                               float64
average_year_eviction_count_svi_economic       float64
change_in_evictions_svi_economic               float64
percent_change_svi_economic                    float64
average_year_eviction_count_svi_demographic    float64
change_in_evictions_svi_demographic            float64
percent_change_svi_demographic                 float64
average_year_eviction_count_svi_household      float64
change_in_evictions_svi_household              float64
percent_change_svi_household                   float64
average_year_eviction_count_svi_racial         float64
change_in_evictions_svi_racial                 float64
percent_change_svi_racial                      float64
original_llc_status                            float64
llc_change                                      object
average_year_eviction_count_llc                float64
change_in_evictions_llc                        float64
percent_change_llc                             float64
original_numfloors                             float64
modified_numfloors                             float64
average_year_eviction_count_numfloors          float64
dtype: object

In [ ]:
# llc_change is boolean currently, we can just drop it for trend analysis
metric_columns2.remove('llc_change')

In [ ]:
trend_analysis_nta = directional_changes(result_df_nta, feature_directions, metric_columns2)

In [ ]:
summary_rows_nta = []

for intervention, stats in trend_analysis_nta.items():
    summary_rows_nta.append({
        'intervention': intervention,
        'buildings with decreased evictions (%)': stats['decreased_evictions']['percentage'],
        'average eviction reduction (%)': stats['decreased_evictions']['avg_reduction'],
        'buildings with increased evictions (%)': stats['increased_evictions']['percentage'],
        'average eviction increase (%)': stats['increased_evictions']['avg_increase']
    })

In [ ]:
trend_summary_nta = pd.DataFrame(summary_rows_nta)
trend_summary_nta = trend_summary_nta.sort_values(by='buildings with decreased evictions (%)', ascending=False)

In [ ]:
trend_summary_nta

intervention  \
0                 average_year_eviction_count_c   
6          average_year_eviction_count_targeted   
3               average_year_eviction_count_c50   
12     average_year_eviction_count_svi_economic   
9                 average_year_eviction_count_s   
18    average_year_eviction_count_svi_household   
15  average_year_eviction_count_svi_demographic   
25              average_year_eviction_count_llc   
30        average_year_eviction_count_numfloors   
29                           modified_numfloors   
28                           original_numfloors   
21       average_year_eviction_count_svi_racial   
4                       change_in_evictions_c50   
5                                           c50   
7                  change_in_evictions_targeted   
8                                      targeted   
10                        change_in_evictions_s   
11                                            s   
13             change_in_evictions_svi_economic   
14                                 svi_economic   
16          change_in_evictions_svi_demographic   
22               change_in_evictions_svi_racial   
17                              svi_demographic   
19            change_in_evictions_svi_household   
23                                   svi_racial   
20                                svi_household   
26                      change_in_evictions_llc   
27                                          llc   
24                          original_llc_status   
1                         change_in_evictions_c   
2                                             c   

    buildings with decreased evictions (%)  average eviction reduction (%)  \
0                                100.00000                         1.88000   
6                                100.00000                         0.91000   
3                                100.00000                         0.81000   
12                               100.00000                         1.16000   
9                                100.00000                         0.94000   
18                               100.00000                         1.17000   
15                               100.00000                         1.15000   
25                               100.00000                         1.19000   
30                               100.00000                         1.19000   
29                               100.00000                         3.22000   
28                               100.00000                         6.43000   
21                               100.00000                         1.15000   
4                                 65.36000                         0.74000   
5                                 65.34000                        36.67000   
7                                 61.37000                         0.67000   
8                                 61.31000                        31.08000   
10                                61.25000                         0.62000   
11                                61.16000                        33.68000   
13                                60.11000                         0.16000   
14                                59.82000                         8.12000   
16                                59.65000                         0.17000   
22                                59.29000                         0.22000   
17                                59.25000                         7.44000   
19                                59.17000                         0.16000   
23                                58.94000                        13.35000   
20                                58.83000                         7.83000   
26                                55.47000                         0.14000   
27                                53.75000                         9.57000   
24                                47.09000                         1.00000   
1                                 42.81000                    

## **Step 6.3: Run Sensitivity analysis on neighborhood result**

In [ ]:
target_neighborhoods = nta_list

In [ ]:
intervention_levels = {}

In [ ]:
# part 1: run sensitivity analysis for different intervention levels

# takes a long time to run due to calling the function for each type for each neighborhood.
# the result will be saved
intervention_levels = {}

for neighborhood in target_neighborhoods:
    neighborhood_df = result_df_nta[result_df_nta['nta'] == neighborhood].copy()
    print(f"inside the outside loop of sensitivity analysis for {neighborhood} with {len(neighborhood_df)} buildings")

    # complaint reduction sensitivity
    complaint_sensitivity = []
    for pct in [25, 50, 75]:
        print(f"inside the loop of complaint reduction at {pct}%")
        result = process_hotspot_counterfactuals(df=neighborhood_df, neighborhoods=target_neighborhoods, rfr_model= model_rfr_all,feature_cols=all_vars, complaints_vars=complaints_vars,
                                                 complaint_reduction_pct=pct)
        col_name = f'percent_change_c{pct}'
        avg_reduction = result[col_name].mean()
        complaint_sensitivity.append((pct, avg_reduction))

    # SVI improvement sensitivity
    svi_sensitivity = []
    for quantile in [0.25, 0.5, 0.75]:
        print(f"inside the loop of SVI improvement at quantile {quantile}")
        result = process_hotspot_counterfactuals( df=neighborhood_df, neighborhoods=target_neighborhoods, rfr_model= model_rfr_all, feature_cols=all_vars, svi_vars=svi_vars, svi_reduction_quantile=quantile)
        avg_reduction = result['percent_change_s'].mean()
        svi_sensitivity.append((quantile, avg_reduction))

    # llc status flipping sensitivity
    print("inside the loop of LLC status flipping")
    result = process_hotspot_counterfactuals(df=neighborhood_df, neighborhoods=target_neighborhoods, rfr_model= model_rfr_all, feature_cols=all_vars,change_llc=True)
    # two scenarios, from 'is llc' to 'not llc'
    # and from 'not llc' to 'is llc'
    llc_buildings = result[result['is_llc'] == True]
    non_llc_buildings = result[result['is_llc'] == False]
    llc_to_non_effect = llc_buildings['percent_change_llc'].mean()
    non_to_llc_effect = non_llc_buildings['percent_change_llc'].mean()
    llc_sensitivity = [('llc_to_non', llc_to_non_effect), ('non_to_llc', non_to_llc_effect)]

    # building age sensitivity
    age_sensitivity = []
    for years in [10, 20, 30]:
        print(f"inside the loop of building age reduction by {years} years")
        result = process_hotspot_counterfactuals(
            df=neighborhood_df,
            neighborhoods=target_neighborhoods,
            rfr_model= model_rfr_all,
            feature_cols=all_vars,
            building_age_change=years
        )
        avg_reduction = result['percent_change_age'].mean()
        age_sensitivity.append((years, avg_reduction))

    # combined building features sensitivity
    building_features_sensitivity = []
    for pct in [30, 50, 70]:
        print(f"inside the loop of combined building feature reduction at {pct}%")
        result = process_hotspot_counterfactuals(
            df=neighborhood_df,
            neighborhoods=target_neighborhoods,
            rfr_model= model_rfr_all,
            feature_cols=all_vars,
            building_change={
                'numfloors': -pct,
                'unitsres': -pct,
                'bldgarea': -pct
            }
        )
        avg_reduction = result['percent_change_bld_all'].mean()
        building_features_sensitivity.append((pct, avg_reduction))

    # separate bldgarea sensitivity
    # easier for gathering all the results into an aggregated dataframe later
    bldgarea_sensitivity = []
    for pct in [30, 50, 70]:
        print(f"inside the loop of bldgarea reduction at {pct}%")
        result = process_hotspot_counterfactuals(
            df=neighborhood_df,
            neighborhoods=target_neighborhoods,
            rfr_model= model_rfr_all,
            feature_cols=all_vars,
            building_change={'bldgarea': -pct}
        )
        avg_reduction = result['percent_change_bld_all'].mean()
        bldgarea_sensitivity.append((pct, avg_reduction))

    # separate unitsres sensitivity
    unitsres_sensitivity = []
    for pct in [30, 50, 70]:
        print(f"inside the loop of unitsres reduction at {pct}%")
        result = process_hotspot_counterfactuals(
            df=neighborhood_df,
            neighborhoods=target_neighborhoods,
            rfr_model= model_rfr_all,
            feature_cols=all_vars,
            building_change={'unitsres': -pct}
        )
        avg_reduction = result['percent_change_bld_all'].mean()
        unitsres_sensitivity.append((pct, avg_reduction))

    # separate numfloors sensitivity
    numfloors_sensitivity = []
    for pct in [30, 50, 70]:
        print(f"inside the loop of numfloors reduction at {pct}%")
        result = process_hotspot_counterfactuals(
            df=neighborhood_df,
            neighborhoods=target_neighborhoods,
            rfr_model= model_rfr_all,
            feature_cols=all_vars,
            building_change={'numfloors': -pct}
        )
        avg_reduction = result['percent_change_bld_all'].mean()
        numfloors_sensitivity.append((pct, avg_reduction))

    # finally, we tore everything to a list so far
    intervention_levels[neighborhood] = {
        'complaint_sensitivity': complaint_sensitivity,
        'svi_sensitivity': svi_sensitivity,
        'llc_sensitivity': llc_sensitivity,
        'age_sensitivity': age_sensitivity,
        # combined
        'building_features_sensitivity': building_features_sensitivity,
        # individuals
        'bldgarea_sensitivity': bldgarea_sensitivity,
        'unitsres_sensitivity': unitsres_sensitivity,
        'numfloors_sensitivity': numfloors_sensitivity
    }

    print(f"done with the loop of {neighborhood}")

inside the outside loop of sensitivity analysis for Central Harlem North-Polo Grounds with 1632 buildings
inside the loop of complaint reduction at 25%
inside the loop of complaint reduction at 50%
inside the loop of complaint reduction at 75%
inside the loop of SVI improvement at quantile 0.25
inside the loop of SVI improvement at quantile 0.5
inside the loop of SVI improvement at quantile 0.75
inside the loop of LLC status flipping
inside the loop of building age reduction by 10 years
inside the loop of building age reduction by 20 years
inside the loop of building age reduction by 30 years
inside the loop of combined building feature reduction at 30%
inside the loop of combined building feature reduction at 50%
inside the loop of combined building feature reduction at 70%
inside the loop of bldgarea reduction at 30%
inside the loop of bldgarea reduction at 50%
inside the loop of bldgarea reduction at 70%
inside the loop of unitsres reduction at 30%
inside the loop of unitsres reduct

In [ ]:
intervention_levels

{'Central Harlem North-Polo Grounds': {'complaint_sensitivity': [(25,
    np.float64(-6.568511029411765)),
   (50, np.float64(-2.2003186274509803)),
   (75, np.float64(1.9561397058823524))],
  'svi_sensitivity': [(0.25, np.float64(-35.873823529411766)),
   (0.5, np.float64(-13.224479166666665)),
   (0.75, np.float64(-23.9684068627451))],
  'llc_sensitivity': [('llc_to_non', np.float64(-17.980793357933578)),
   ('non_to_llc', np.float64(-16.049137614678898))],
  'age_sensitivity': [(10, np.float64(-63.62705269607844)),
   (20, np.float64(-96.53775122549018)),
   (30, np.float64(-107.17489583333332))],
  'building_features_sensitivity': [(30, np.float64(-7.267530637254902)),
   (50, np.float64(-6.284944852941177)),
   (70, np.float64(-7.4486580882352955))],
  'bldgarea_sensitivity': [(30, np.float64(-96.07960171568625)),
   (50, np.float64(-96.07960171568625)),
   (70, np.float64(-96.07960171568625))],
  'unitsres_sensitivity': [(30, np.float64(-96.07960171568625)),
   (50, np.float64(-9

In [ ]:
flat_records = []

In [ ]:
intervention_name_map = {'complaint_sensitivity': 'complaint reduction', 'svi_sensitivity': 'SVI improvement', 'llc_sensitivity': 'LLC Status Change',
    'age_sensitivity': 'building age reduction', 'building_features_sensitivity': 'all building features','bldgarea_sensitivity': 'bldgarea reduction',
    'unitsres_sensitivity': 'unitsres reduction', 'numfloors_sensitivity': 'numFloors reduction'}

In [ ]:
for neighborhood, sensitivity_dict in intervention_levels.items():
    for key, values in sensitivity_dict.items():
        feature_name = intervention_name_map.get(key, key)
        for change, effect in values:
            flat_records.append({'neighborhood': neighborhood, 'intervention': feature_name, 'variant': change, 'effect': float(effect),
                                 'feature': key.replace('_sensitivity', '')})

In [ ]:
intervention_df = pd.DataFrame(flat_records)

In [ ]:
intervention_df = intervention_df.sort_values(by=['neighborhood', 'intervention', 'variant']).reset_index(drop=True)
intervention_df.shape

(69, 5)

In [ ]:
intervention_df

neighborhood            intervention     variant  \
0          Bedford Park-Fordham North       LLC Status Change  llc_to_non   
1          Bedford Park-Fordham North       LLC Status Change  non_to_llc   
2          Bedford Park-Fordham North         SVI improvement     0.25000   
3          Bedford Park-Fordham North         SVI improvement     0.50000   
4          Bedford Park-Fordham North         SVI improvement     0.75000   
5          Bedford Park-Fordham North   all building features          30   
6          Bedford Park-Fordham North   all building features          50   
7          Bedford Park-Fordham North   all building features          70   
8          Bedford Park-Fordham North      bldgarea reduction          30   
9          Bedford Park-Fordham North      bldgarea reduction          50   
10         Bedford Park-Fordham North      bldgarea reduction          70   
11         Bedford Park-Fordham North  building age reduction          10   
12         Bedford Park-Fordham North  building age reduction          20   
13         Bedford Park-Fordham North  building age reduction          30   
14         Bedford Park-Fordham North     complaint reduction          25   
15         Bedford Park-Fordham North     complaint reduction          50   
16         Bedford Park-Fordham North     complaint reduction          75   
17         Bedford Park-Fordham North     numFloors reduction          30   
18         Bedford Park-Fordham North     numFloors reduction          50   
19         Bedford Park-Fordham North     numFloors reduction          70   
20         Bedford Park-Fordham North      unitsres reduction          30   
21         Bedford Park-Fordham North      unitsres reduction          50   
22         Bedford Park-Fordham North      unitsres reduction          70   
23  Central Harlem North-Polo Grounds       LLC Status Change  llc_to_non   
24  Central Harlem North-Polo Grounds       LLC Status Change  non_to_llc   
25  Central Harlem North-Polo Grounds         SVI improvement     0.25000   
26  Central Harlem North-Polo Grounds         SVI improvement     0.50000   
27  Central Harlem North-Polo Grounds         SVI improvement     0.75000   
28  Central Harlem North-Polo Grounds   all building features          30   
29  Central Harlem North-Polo Grounds   all building features          50   
30  Central Harlem North-Polo Grounds   all building features          70   
31  Central Harlem North-Polo Grounds      bldgarea reduction          30   
32  Central Harlem North-Polo Grounds      bldgarea reduction          50   
33  Central Harlem North-Polo Grounds      bldgarea reduction          70   
34  Central Harlem North-Polo Grounds  building age reduction          10   
35  Central Harlem North-Polo Grounds  building age reduction          20   
36  Central Harlem North-Polo Grounds  building age reduction          30   
37  Central Harlem North-Polo Grounds     complaint reduction          25   
38  Central Harlem North-Polo Grounds     complaint reduction          50   
39  Central Harlem North-Polo Grounds     complaint reduction          75   
40  Central Harlem North-Polo Grounds     numFloors reduction          30   
41  Central Harlem North-Polo Grounds     numFloors reduction          50   
42  Central Harlem North-Polo Grounds     numFloors reduction          70   
43  Central Harlem North-Polo Grounds      unitsres reduction          30   
44  Central Harlem North-Polo Grounds      unitsres reduction          50   
45  Central Harlem North-Polo Grounds      unitsres reduction          70   
46                Crown Heights North       LLC Status Change  llc_to_non   
47                Crown Heights North       LLC Status Change  non_to_llc   
48                Crown Heights North         SVI improvement     0.25000   
49                Crown Heights North         SVI improvement     0.50000   
50                Crown Heights North         SVI improvement     0.75000   
51                Cro

In [ ]:
intervention_df_reduced = intervention_df[~((intervention_df['intervention'] == 'bldgarea reduction') | (intervention_df['intervention'] == 'unitsres reduction') \
                                    | (intervention_df['intervention'] == 'numFloors reduction') )]
# as we can see, many of the individual building features are way too "influential" and therefore we will only keep the combined ones that are more moderate

In [ ]:
intervention_df_reduced.shape, intervention_df.shape

((42, 5), (69, 5))

In [ ]:
intervention_df_reduced

neighborhood            intervention     variant  \
0          Bedford Park-Fordham North       LLC Status Change  llc_to_non   
1          Bedford Park-Fordham North       LLC Status Change  non_to_llc   
2          Bedford Park-Fordham North         SVI improvement     0.25000   
3          Bedford Park-Fordham North         SVI improvement     0.50000   
4          Bedford Park-Fordham North         SVI improvement     0.75000   
5          Bedford Park-Fordham North   all building features          30   
6          Bedford Park-Fordham North   all building features          50   
7          Bedford Park-Fordham North   all building features          70   
11         Bedford Park-Fordham North  building age reduction          10   
12         Bedford Park-Fordham North  building age reduction          20   
13         Bedford Park-Fordham North  building age reduction          30   
14         Bedford Park-Fordham North     complaint reduction          25   
15         Bedford Park-Fordham North     complaint reduction          50   
16         Bedford Park-Fordham North     complaint reduction          75   
23  Central Harlem North-Polo Grounds       LLC Status Change  llc_to_non   
24  Central Harlem North-Polo Grounds       LLC Status Change  non_to_llc   
25  Central Harlem North-Polo Grounds         SVI improvement     0.25000   
26  Central Harlem North-Polo Grounds         SVI improvement     0.50000   
27  Central Harlem North-Polo Grounds         SVI improvement     0.75000   
28  Central Harlem North-Polo Grounds   all building features          30   
29  Central Harlem North-Polo Grounds   all building features          50   
30  Central Harlem North-Polo Grounds   all building features          70   
34  Central Harlem North-Polo Grounds  building age reduction          10   
35  Central Harlem North-Polo Grounds  building age reduction          20   
36  Central Harlem North-Polo Grounds  building age reduction          30   
37  Central Harlem North-Polo Grounds     complaint reduction          25   
38  Central Harlem North-Polo Grounds     complaint reduction          50   
39  Central Harlem North-Polo Grounds     complaint reduction          75   
46                Crown Heights North       LLC Status Change  llc_to_non   
47                Crown Heights North       LLC Status Change  non_to_llc   
48                Crown Heights North         SVI improvement     0.25000   
49                Crown Heights North         SVI improvement     0.50000   
50                Crown Heights North         SVI improvement     0.75000   
51                Crown Heights North   all building features          30   
52                Crown Heights North   all building features          50   
53                Crown Heights North   all building features          70   
57                Crown Heights North  building age reduction          10   
58                Crown Heights North  building age reduction          20   
59                Crown Heights North  building age reduction          30   
60                Crown Heights North     complaint reduction          25   
61                Crown Heights North     complaint reduction          50   
62                Crown Heights North     complaint reduction          75   

       effect            feature  
0    -7.40934                llc  
1   -30.21035                llc  
2   -19.06828                svi  
3   -19.06828                svi  
4   -19.06828                svi  
5    -7.78960  building_features  
6     0.13767  building_features  
7     6.81297  building_features  
11  -70.15365                age  
12  -96.98458                age  
13 -102.70509                age  
14   -6.60408          complaint  
15   -2.68792          complaint  
16   -2.59239          complaint  
23  -17.98079                llc  
24  -16.04914                llc  
25  -35.87382                svi  
26  -13.22448                svi  
27  -23.96841                svi  
28   -7.26753

In [ ]:
intervention_df_reduced.columns

Index(['neighborhood', 'intervention', 'variant', 'effect', 'feature'], dtype='object')

In [ ]:
intervention_df.to_csv('/content/drive/My Drive/X999/intervention_df_indiviudals.csv')

In [ ]:
intervention_df_reduced.to_csv('/content/drive/My Drive/X999/intervention_df_indiviudals_reduced.csv')

In [ ]:
intervention_levels_df.to_csv('/content/drive/My Drive/X999/intervention_levels_df.csv')
# a df we got from a previous run, the codes have been changed and not kept here (to rerun will take a long time, and
# it is basically the same dataframe as the one above but without the detailed building feature ones. For clarity, we kept this df here.)
# if we ignore the individual effects and only consider the combined building feature change effects
# this combined effect makes more sense, because when building size shrinks, the number of floors also decreases
# and the total units must also shrink. So the prediction based upon the three factors together would be more sensible
# this is the dataframe we had from previous runs where we did not add back the individual building feature changes and the results are more
# clear and moderate
intervention_levels_df
# this is outdated, but let's keep it here for now for reference

neighborhood                       category  \
0   Central Harlem North-Polo Grounds          complaint_sensitivity   
1   Central Harlem North-Polo Grounds          complaint_sensitivity   
2   Central Harlem North-Polo Grounds          complaint_sensitivity   
3   Central Harlem North-Polo Grounds                svi_sensitivity   
4   Central Harlem North-Polo Grounds                svi_sensitivity   
5   Central Harlem North-Polo Grounds                svi_sensitivity   
6   Central Harlem North-Polo Grounds                llc_sensitivity   
7   Central Harlem North-Polo Grounds                llc_sensitivity   
8   Central Harlem North-Polo Grounds                age_sensitivity   
9   Central Harlem North-Polo Grounds                age_sensitivity   
10  Central Harlem North-Polo Grounds                age_sensitivity   
11  Central Harlem North-Polo Grounds  building_features_sensitivity   
12  Central Harlem North-Polo Grounds  building_features_sensitivity   
13  Central Harlem North-Polo Grounds  building_features_sensitivity   
14                Crown Heights North          complaint_sensitivity   
15                Crown Heights North          complaint_sensitivity   
16                Crown Heights North          complaint_sensitivity   
17                Crown Heights North                svi_sensitivity   
18                Crown Heights North                svi_sensitivity   
19                Crown Heights North                svi_sensitivity   
20                Crown Heights North                llc_sensitivity   
21                Crown Heights North                llc_sensitivity   
22                Crown Heights North                age_sensitivity   
23                Crown Heights North                age_sensitivity   
24                Crown Heights North                age_sensitivity   
25                Crown Heights North  building_features_sensitivity   
26                Crown Heights North  building_features_sensitivity   
27                Crown Heights North  building_features_sensitivity   
28         Bedford Park-Fordham North          complaint_sensitivity   
29         Bedford Park-Fordham North          complaint_sensitivity   
30         Bedford Park-Fordham North          complaint_sensitivity   
31         Bedford Park-Fordham North                svi_sensitivity   
32         Bedford Park-Fordham North                svi_sensitivity   
33         Bedford Park-Fordham North                svi_sensitivity   
34         Bedford Park-Fordham North                llc_sensitivity   
35         Bedford Park-Fordham North                llc_sensitivity   
36         Bedford Park-Fordham North                age_sensitivity   
37         Bedford Park-Fordham North                age_sensitivity   
38         Bedford Park-Fordham North                age_sensitivity   
39         Bedford Park-Fordham North  building_features_sensitivity   
40         Bedford Park-Fordham North  building_features_sensitivity   
41         Bedford Park-Fordham North  building_features_sensitivity   
42  Central Harlem North-Polo Grounds          complaint_sensitivity   
43  Central Harlem North-Polo Grounds          complaint_sensitivity   
44  Central Harlem North-Polo Grounds          complaint_sensitivity   
45  Central Harlem North-Polo Grounds                svi_sensitivity   
46  Central Harlem North-Polo Grounds                svi_sensitivity   
47  Central Harlem North-Polo Grounds                svi_sensitivity   
48  Central Harlem North-Polo Grounds                llc_sensitivity   
49  Central Harlem North-Polo Grounds                llc_sensitivity   
50  Central Harlem North-Polo Grounds                age_sensitivity   
51  Central Harlem North-Polo Grounds                age_sensitivity   
52  Central Harlem North-Polo Grounds                age_sensitivity   
53  Central Harlem North-Polo Grounds  building_features_sensitivity   
54  Central Harlem North-Polo Grounds  building_features_sensitiv

In [ ]:
# mini_tables
ranking_records = []

In [ ]:
building_type_analysis = {}
intervention_ranking_records = []

In [ ]:
# define mapping for intervention display names
intervention_names = {
    'c': 'complaint reduction',
    's': 'SVI improvement',
    'llc': 'llc status change',
    'age': 'building age reduction',
    'bld_all': 'all building changes'
}

In [ ]:
for neighborhood in target_neighborhoods:
    neighborhood_df = result_df_nta[result_df_nta['nta'] == neighborhood]
    building_col = None

    # identify the correct building type column
    for col in ['building_category', 'building_type', 'building_size_category']:
        if col in neighborhood_df.columns:
            building_col = col
            break

    if building_col is None:
        print(f"No building category column found for {neighborhood}. Skipping...")
        continue

    building_analysis = neighborhood_df.groupby(building_col).agg({
        'original_eviction_count': 'sum',
        'bin': 'count'
    }).rename(columns={'bin': 'building_count'})

    # add intervention effect columns
    for suffix in ['c', 's', 'llc', 'age', 'bld_all']:
        col_name = f'average_year_eviction_count_{suffix}'
        if col_name in neighborhood_df.columns:
            building_analysis[col_name] = neighborhood_df.groupby(building_col)[col_name].sum()

    # percent reductions
    for suffix in ['c', 's', 'llc', 'age', 'bld_all']:
        col_name = f'average_year_eviction_count_{suffix}'
        if col_name in building_analysis.columns:
            with np.errstate(divide='ignore', invalid='ignore'):
                building_analysis[f'percent_change_{suffix}'] = (
                    (building_analysis['original_eviction_count'] - building_analysis[col_name]) /
                    building_analysis['original_eviction_count'].replace(0, np.nan) * 100
                ).round(2)

    # determine best and second-best interventions
    pct_columns = [col for col in building_analysis.columns if col.startswith('percent_change_')]
    if pct_columns:
        building_analysis['best_intervention'] = building_analysis[pct_columns].idxmax(axis=1)
        building_analysis['best_intervention'] = building_analysis['best_intervention'].str.replace('percent_change_', '')

        building_analysis['max_reduction_pct'] = building_analysis[pct_columns].max(axis=1)

        # for second-best intervention
        pct_df = building_analysis[pct_columns].copy()
        for idx in pct_df.index:
            best_col_suffix = building_analysis.loc[idx, 'best_intervention']
            best_col_full = f'percent_change_{best_col_suffix}'
            pct_df.loc[idx, best_col_full] = np.nan

        building_analysis['second_best_intervention'] = pct_df.idxmax(axis=1).str.replace('percent_change_', '')
        building_analysis['second_max_reduction_pct'] = pct_df.max(axis=1)

    building_type_analysis[neighborhood] = building_analysis

    # now collect full rankings for all building types and interventions
    for intervention in ['c', 's', 'llc', 'age', 'bld_all']:
        col = f'percent_change_{intervention}'
        if col not in building_analysis.columns:
            continue

        intervention_name = intervention_names.get(intervention, intervention)

        sorted_building_analysis = building_analysis.sort_values(col, ascending=False).reset_index()

        for rank, row in sorted_building_analysis.iterrows():
            reduction = row[col]
            if not pd.isna(reduction):
                intervention_ranking_records.append({
                    'neighborhood': neighborhood,
                    'intervention_type': intervention_name,
                    'building_type': row[building_col],
                    'reduction_pct': reduction,
                    'rank': rank + 1,
                    'building_count': row['building_count'],
                    'eviction_count': row['original_eviction_count']
                })

In [ ]:
for neighborhood in target_neighborhoods:
    building_analysis = building_type_analysis.get(neighborhood)

    for intervention in ['c', 's', 'llc', 'age', 'bld_all']:
        col = f'percent_change_{intervention}'
        if col not in building_analysis.columns:
            continue
        intervention_name = intervention_names.get(intervention, intervention)
        sorted_df = building_analysis.sort_values(col, ascending=False).reset_index()
        for rank, row in sorted_df.iterrows():
            btype = row[building_analysis.index.name or 'index']
            reduction = row[col]
            record = {'neighborhood': neighborhood, 'intervention_type': intervention_name, 'building_type': btype,
                'reduction_pct': None if pd.isna(reduction) else round(reduction, 2), 'rank': rank + 1, 'building_count': int(row['building_count']),
                'eviction_count': float(row['original_eviction_count'])}
            ranking_records.append(record)

In [ ]:
ranking_df = pd.DataFrame(ranking_records)
ranking_df.shape

(85, 7)

In [ ]:
ranking_df

neighborhood       intervention_type  \
0   Central Harlem North-Polo Grounds     complaint reduction   
1   Central Harlem North-Polo Grounds     complaint reduction   
2   Central Harlem North-Polo Grounds     complaint reduction   
3   Central Harlem North-Polo Grounds     complaint reduction   
4   Central Harlem North-Polo Grounds     complaint reduction   
5   Central Harlem North-Polo Grounds         SVI improvement   
6   Central Harlem North-Polo Grounds         SVI improvement   
7   Central Harlem North-Polo Grounds         SVI improvement   
8   Central Harlem North-Polo Grounds         SVI improvement   
9   Central Harlem North-Polo Grounds         SVI improvement   
10  Central Harlem North-Polo Grounds       llc status change   
11  Central Harlem North-Polo Grounds       llc status change   
12  Central Harlem North-Polo Grounds       llc status change   
13  Central Harlem North-Polo Grounds       llc status change   
14  Central Harlem North-Polo Grounds       llc status change   
15  Central Harlem North-Polo Grounds  building age reduction   
16  Central Harlem North-Polo Grounds  building age reduction   
17  Central Harlem North-Polo Grounds  building age reduction   
18  Central Harlem North-Polo Grounds  building age reduction   
19  Central Harlem North-Polo Grounds  building age reduction   
20  Central Harlem North-Polo Grounds    all building changes   
21  Central Harlem North-Polo Grounds    all building changes   
22  Central Harlem North-Polo Grounds    all building changes   
23  Central Harlem North-Polo Grounds    all building changes   
24  Central Harlem North-Polo Grounds    all building changes   
25                Crown Heights North     complaint reduction   
26                Crown Heights North     complaint reduction   
27                Crown Heights North     complaint reduction   
28                Crown Heights North     complaint reduction   
29                Crown Heights North     complaint reduction   
30                Crown Heights North     complaint reduction   
31                Crown Heights North         SVI improvement   
32                Crown Heights North         SVI improvement   
33                Crown Heights North         SVI improvement   
34                Crown Heights North         SVI improvement   
35                Crown Heights North         SVI improvement   
36                Crown Heights North         SVI improvement   
37                Crown Heights North       llc status change   
38                Crown Heights North       llc status change   
39                Crown Heights North       llc status change   
40                Crown Heights North       llc status change   
41                Crown Heights North       llc status change   
42                Crown Heights North       llc status change   
43                Crown Heights North  building age reduction   
44                Crown Heights North  building age reduction   
45                Crown Heights North  building age reduction   
46                Crown Heights North  building age reduction   
47                Crown Heights North  building age reduction   
48                Crown Heights North  building age reduction   
49                Crown Heights North    all building changes   
50                Crown Heights North    all building changes   
51                Crown Heights North    all building changes   
52                Crown Heights North    all building changes   
53                Crown Heights North    all building changes   
54                Crown Heights North    all building changes   
55         Bedford Park-Fordham North     complaint reduction   
56         Bedford Park-Fordham North     complaint reduction   
57         Bedford Park-Fordham North     complaint reduction   
58         Bedford Park-Fordham North     complaint reduction   
59         Bedford Park-Fordham North     complaint reduction   
60         Bedford Park-Fordham North     complaint reductio

In [ ]:
intervention_ranking_df = pd.DataFrame(intervention_ranking_records)
intervention_ranking_df.head()

neighborhood    intervention_type  \
0  Central Harlem North-Polo Grounds  complaint reduction   
1  Central Harlem North-Polo Grounds  complaint reduction   
2  Central Harlem North-Polo Grounds  complaint reduction   
3  Central Harlem North-Polo Grounds  complaint reduction   
4  Central Harlem North-Polo Grounds  complaint reduction   

                  building_type  reduction_pct  rank  building_count  \
0                      elevator          44.49     1             735   
1                       walk-up          24.25     2             801   
2                   condo-co-op          15.46     3              85   
3                    two-family         -84.47     4               3   
4  primarily_res_with_mixed_use        -105.91     5               8   

   eviction_count  
0          1602.6  
1           591.0  
2           105.0  
3             0.6  
4             1.6

In [ ]:
intervention_ranking_df.to_csv("intervention_ranking_by_building_type.csv", index=False)

In [ ]:
building_analysis.sort_values('max_reduction_pct', ascending=False)

original_eviction_count  building_count  \
building_category                                                       
primarily_res_with_mixed_use                      8.4              14   
condo-co-op                                      36.8              42   
two-family                                       14.6              33   
walk-up                                         947.2             816   
elevator                                       1035.2             616   
single-family                                     2.2               9   

                              average_year_eviction_count_c  \
building_category                                             
primarily_res_with_mixed_use                      17.259916   
condo-co-op                                       77.589668   
two-family                                        16.723236   
walk-up                                         1503.182983   
elevator                                        1584.268799   
single-family                                      5.050557   

                              average_year_eviction_count_s  \
building_category                                             
primarily_res_with_mixed_use                       4.583329   
condo-co-op                                       25.427605   
two-family                                         9.744430   
walk-up                                          643.492493   
elevator                                         721.171570   
single-family                                      3.098861   

                              average_year_eviction_count_llc  \
building_category                                               
primarily_res_with_mixed_use                         5.758747   
condo-co-op                                         42.468140   
two-family                                          21.720274   
walk-up                                            917.414001   
elevator                                           992.136963   
single-family                                        5.821255   

                              average_year_eviction_count_age  \
building_category                                               
primarily_res_with_mixed_use                        58.230602   
condo-co-op                                         41.236576   
two-family                                          79.472794   
walk-up                                           1017.300964   
elevator                                          1208.093628   
single-family                                        4.152866   

                              average_year_eviction_count_bld_all  \
building_category                                                   
primarily_res_with_mixed_use                            59.556992   
condo-co-op                                             23.534353   
two-family                                              79.472794   
walk-up                                                840.709290   
elevator                                              1224.339111   
single-family                                            4.152866   

                              percent_change_c  percent_change_s  \
building_category                                                  
primarily_res_with_mixed_use           -105.48             45.44   
condo-co-op                            -110.84             30.90   
two-family                              -14.54             33.26   
walk-up                                 -58.70             32.06   
elevator                                -53.04             30.34   
single-family                          -129.57            -40.86   

                              percent_change_llc  percent_change_age  \
building_category                                                      
primarily_res_with_mixed_use               31.44             -593.22   
condo-co-op                               -15.40              -12.06   
two-fam

# **Base on these results, here are summaries based on how each type of reduction would affect different categories' buildings in three of the hardest eviction hit neighborhoods: Central Harlem, Crown Heights North, and Bedford Park-Fordham North:**

### *These are the "What if scenarios": what if certain types of complaints go down? What if svi scores go down? What if buildings were newer? What if the buildings downsized? What if SVI scores only went down xx% but several complaints go to 0? What if all complaints were reduced to 0? What if the ownership of the building has changed? What if these same changes happen to different categories of buildings (such as walk-up and elevators), and how would they react different to the changes? Who would be the most resilient types of buildings? etc.*

### Previously, we have already known the overal trends when these factors decrease. By using the core function and adjusting the **geo parameters (neighborhoods, zipcodes, or building ids)**, **feature selections (complaints, svi scores, building age, is_llc, building units, building areas, and building heights)**, and the **degree and direction of change (yes-> no, no-> yes, 25%, 50%, 75% reductions for each featrues etc.)**, we got detailed breakdowns of how exactly the effects would be to these particular eviction hotspots.

### In future notebooks, we will carry out experiments and analysis on eviction hotspots (in terms of building ids) and eviction coldspots (in terms of neighborhoods and building ids), using the same core functions, to come up with scenarios where different feature variants, directions of changes, and degrees of changes. (may or may not upload the experiments here).

## **Intervention Effectiveness by Building Type for Central Harlem North-Polo Grounds**

--- Complaint Reduction ---
1. elevator: 44.49% reduction (735 buildings, 1602.6 evictions)
2. walk-up: 24.25% reduction (801 buildings, 591.0 evictions)
3. condo-co-op: 15.46% reduction (85 buildings, 105.0 evictions)
4. two-family: -84.47% reduction (3 buildings, 0.6 evictions)
5. primarily_res_with_mixed_use: -105.91% reduction (8 buildings, 1.6 evictions)

--- SVI Improvement ---
1. condo-co-op: 28.13% reduction (85 buildings, 105.0 evictions)
2. elevator: 27.38% reduction (735 buildings, 1602.6 evictions)
3. walk-up: 22.81% reduction (801 buildings, 591.0 evictions)
4. two-family: -42.23% reduction (3 buildings, 0.6 evictions)
5. primarily_res_with_mixed_use: -59.78% reduction (8 buildings, 1.6 evictions)

--- LLC Status Change ---
1. walk-up: 3.67% reduction (801 buildings, 591.0 evictions)
2. elevator: -0.78% reduction (735 buildings, 1602.6 evictions)
3. condo-co-op: -23.32% reduction (85 buildings, 105.0 evictions)
4. primarily_res_with_mixed_use: -76.09% reduction (8 buildings, 1.6 evictions)
5. two-family: -107.76% reduction (3 buildings, 0.6 evictions)

--- Building Age Reduction ---
1. walk-up: 5.22% reduction (801 buildings, 591.0 evictions)
2. condo-co-op: -24.69% reduction (85 buildings, 105.0 evictions)
3. elevator: -65.97% reduction (735 buildings, 1602.6 evictions)
4. two-family: -84.09% reduction (3 buildings, 0.6 evictions)
5. primarily_res_with_mixed_use: -690.73% reduction (8 buildings, 1.6 evictions)

--- All Building Changes ---
1. walk-up: 22.21% reduction (801 buildings, 591.0 evictions)
2. condo-co-op: -29.14% reduction (85 buildings, 105.0 evictions)
3. elevator: -58.71% reduction (735 buildings, 1602.6 evictions)
4. two-family: -82.60% reduction (3 buildings, 0.6 evictions)
5. primarily_res_with_mixed_use: -648.54% reduction (8 buildings, 1.6 evictions)

## **Intervention Effectiveness by Building Type for Crown Heights North**

--- Complaint Reduction ---
1. elevator: 23.72% reduction (381 buildings, 610.2 evictions)
2. walk-up: 22.46% reduction (941 buildings, 631.8 evictions)
3. condo-co-op: 12.94% reduction (51 buildings, 31.8 evictions)
4. two-family: 8.14% reduction (126 buildings, 48.0 evictions)
5. primarily_res_with_mixed_use: -3.23% reduction (89 buildings, 30.6 evictions)
6. single-family: -32.17% reduction (11 buildings, 2.6 evictions)

--- SVI Improvement ---
1. elevator: 26.19% reduction (381 buildings, 610.2 evictions)
2. two-family: 23.53% reduction (126 buildings, 48.0 evictions)
3. walk-up: 15.82% reduction (941 buildings, 631.8 evictions)
4. primarily_res_with_mixed_use: 8.48% reduction (89 buildings, 30.6 evictions)
5. condo-co-op: -3.20% reduction (51 buildings, 31.8 evictions)
6. single-family: -17.54% reduction (11 buildings, 2.6 evictions)

--- LLC Status Change ---
1. walk-up: 9.49% reduction (941 buildings, 631.8 evictions)
2. two-family: -4.87% reduction (126 buildings, 48.0 evictions)
3. primarily_res_with_mixed_use: -7.45% reduction (89 buildings, 30.6 evictions)
4. elevator: -7.86% reduction (381 buildings, 610.2 evictions)
5. condo-co-op: -9.10% reduction (51 buildings, 31.8 evictions)
6. single-family: -67.38% reduction (11 buildings, 2.6 evictions)

--- Building Age Reduction ---
1. single-family: -33.96% reduction (11 buildings, 2.6 evictions)
2. elevator: -78.21% reduction (381 buildings, 610.2 evictions)
3. primarily_res_with_mixed_use: -125.37% reduction (89 buildings, 30.6 evictions)
4. condo-co-op: -133.15% reduction (51 buildings, 31.8 evictions)
5. walk-up: -218.60% reduction (941 buildings, 631.8 evictions)
6. two-family: -581.52% reduction (126 buildings, 48.0 evictions)

--- All Building Changes ---
1. single-family: -33.96% reduction (11 buildings, 2.6 evictions)
2. elevator: -69.21% reduction (381 buildings, 610.2 evictions)
3. primarily_res_with_mixed_use: -122.72% reduction (89 buildings, 30.6 evictions)
4. condo-co-op: -174.00% reduction (51 buildings, 31.8 evictions)
5. walk-up: -219.30% reduction (941 buildings, 631.8 evictions)
6. two-family: -574.18% reduction (126 buildings, 48.0 evictions)

## **Intervention Effectiveness by Building Type for Bedford Park-Fordham North**

--- Complaint Reduction ---
1. two-family: -14.54% reduction (33 buildings, 14.6 evictions)
2. elevator: -53.04% reduction (616 buildings, 1035.2 evictions)
3. walk-up: -58.70% reduction (816 buildings, 947.2 evictions)
4. primarily_res_with_mixed_use: -105.48% reduction (14 buildings, 8.4 evictions)
5. condo-co-op: -110.84% reduction (42 buildings, 36.8 evictions)
6. single-family: -129.57% reduction (9 buildings, 2.2 evictions)

--- SVI Improvement ---
1. primarily_res_with_mixed_use: 45.44% reduction (14 buildings, 8.4 evictions)
2. two-family: 33.26% reduction (33 buildings, 14.6 evictions)
3. walk-up: 32.06% reduction (816 buildings, 947.2 evictions)
4. condo-co-op: 30.90% reduction (42 buildings, 36.8 evictions)
5. elevator: 30.34% reduction (616 buildings, 1035.2 evictions)
6. single-family: -40.86% reduction (9 buildings, 2.2 evictions)

--- LLC Status Change ---
1. primarily_res_with_mixed_use: 31.44% reduction (14 buildings, 8.4 evictions)
2. elevator: 4.16% reduction (616 buildings, 1035.2 evictions)
3. walk-up: 3.14% reduction (816 buildings, 947.2 evictions)
4. condo-co-op: -15.40% reduction (42 buildings, 36.8 evictions)
5. two-family: -48.77% reduction (33 buildings, 14.6 evictions)
6. single-family: -164.60% reduction (9 buildings, 2.2 evictions)

--- Building Age Reduction ---
1. walk-up: -7.40% reduction (816 buildings, 947.2 evictions)
2. condo-co-op: -12.06% reduction (42 buildings, 36.8 evictions)
3. elevator: -16.70% reduction (616 buildings, 1035.2 evictions)
4. single-family: -88.77% reduction (9 buildings, 2.2 evictions)
5. two-family: -444.33% reduction (33 buildings, 14.6 evictions)
6. primarily_res_with_mixed_use: -593.22% reduction (14 buildings, 8.4 evictions)

--- All Building Changes ---
1. condo-co-op: 36.05% reduction (42 buildings, 36.8 evictions)
2. walk-up: 11.24% reduction (816 buildings, 947.2 evictions)
3. elevator: -18.27% reduction (616 buildings, 1035.2 evictions)
4. single-family: -88.77% reduction (9 buildings, 2.2 evictions)
5. two-family: -444.33% reduction (33 buildings, 14.6 evictions)
6. primarily_res_with_mixed_use: -609.01% reduction (14 buildings, 8.4 evictions)